# Generated by Django 3.2.8 on 2021-11-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.CharField(default='NONE', max_length=64, verbose_name='邮箱')),
                ('image', models.FileField(default='user_image/default.png', upload_to='user_image', verbose_name='邮箱')),
                ('money', models.FloatField(default=0, verbose_name='余额')),
                ('status', models.CharField(default='on', max_length=3, verbose_name='状态')),
            ],
        ),
    ]
