# Generated by Django 3.2.8 on 2021-11-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(default='user_image/default.png', upload_to='user_image', verbose_name='头像'),
        ),
    ]
