# Generated by Django 3.2.8 on 2021-11-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='off', max_length=3, verbose_name='状态'),
        ),
    ]
