# Generated by Django 3.2.8 on 2021-11-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('username', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email_proved',
            field=models.CharField(default='off', max_length=3, verbose_name='邮箱状态'),
        ),
    ]
