# Generated by Django 3.2.8 on 2021-11-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='anonymity',
            field=models.CharField(default='', max_length=50),
        ),
    ]
