# Generated by Django 3.2.8 on 2021-12-04 11:34

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_auto_20211204_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.IntegerField(verbose_name='商品')),
                ('title', models.CharField(max_length=16, verbose_name='商品名')),
                ('seller', models.IntegerField(verbose_name='卖家')),
                ('buyer', models.IntegerField(verbose_name='买家')),
                ('date', models.DateTimeField(verbose_name='创建时间')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('price', models.FloatField(verbose_name='单价')),
                ('status', models.CharField(default='on', max_length=3, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='default.png', upload_to='goods_image', verbose_name='图像')),
                ('title', models.CharField(max_length=16, verbose_name='商品名')),
                ('detail', tinymce.models.HTMLField(max_length=512, verbose_name='描述')),
                ('label', models.CharField(max_length=32, verbose_name='标签')),
                ('date', models.DateTimeField(verbose_name='创建时间')),
                ('price', models.FloatField(verbose_name='单价')),
                ('amount', models.IntegerField(verbose_name='余量')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
