# Generated by Django 3.2.8 on 2021-12-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='status',
            field=models.CharField(default='off', max_length=3, verbose_name='状态'),
        ),
    ]
