# Generated by Django 3.2.8 on 2021-12-09 21:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_image'),
        ('trade', '0002_goods_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.IntegerField(verbose_name='商品')),
                ('seller', models.IntegerField(verbose_name='卖家')),
                ('date', models.DateTimeField(default=datetime.date(1111, 11, 11), verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
