# Generated by Django 3.2.8 on 2021-12-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='not_deal', max_length=8, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='date',
            field=models.DateTimeField(verbose_name='收藏时间'),
        ),
    ]
