# Generated by Django 3.2.8 on 2021-12-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20211204_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=32, verbose_name='标题'),
        ),
    ]
