# Generated by Django 3.2.8 on 2021-10-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_anonymity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='anonymity',
            field=models.CharField(max_length=50),
        ),
    ]
