# Generated by Django 3.2.8 on 2021-11-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
